# Generated by Django 4.0 on 2022-01-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleadmin',
            old_name='owner',
            new_name='ad_owner',
        ),
        migrations.AddField(
            model_name='peopletechsupport',
            name='ts_owner',
            field=models.IntegerField(default=1, verbose_name='People Owner'),
        ),
    ]
