# Generated by Django 4.0 on 2022-01-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_users_venue_event_attendees_alter_event_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
