# Generated by Django 4.0 on 2022-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
