# Generated by Django 4.0 on 2022-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_peopleadmin_ad_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleadmin',
            name='ad_owner',
            field=models.IntegerField(default=1, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='peopletechsupport',
            name='ts_owner',
            field=models.IntegerField(default=1, verbose_name='Owner'),
        ),
    ]
