# Generated by Django 4.0 on 2022-01-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0004_alter_venue_contact_no_alter_venue_venue_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
