# Generated by Django 4.0 on 2022-01-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0005_rename_user_siteuser_alter_event_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=120)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.people')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
