# Generated by Django 4.0 on 2022-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_people_project_delete_event_delete_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='people',
        ),
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to='events.People'),
        ),
    ]
