# Generated by Django 4.0 on 2022-02-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0006_alter_peopletechsupport_ts_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=120)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
                ('project_experience', models.TextField(default=1, max_length=300)),
                ('ad_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='peopleadmin',
            name='ad_owner',
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
        migrations.AddField(
            model_name='peopletechsupport',
            name='project_experience',
            field=models.TextField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.peopleadministration'),
        ),
        migrations.DeleteModel(
            name='PeopleAdmin',
        ),
    ]
