# Generated by Django 4.0 on 2022-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_project_people_project_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(blank=True, to='events.People'),
        ),
    ]
