# Generated by Django 4.0 on 2022-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_peopleadministration_remove_peopleadmin_ad_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleadministration',
            name='project_experience',
            field=models.TextField(default='experience', max_length=300),
        ),
        migrations.AlterField(
            model_name='peopletechsupport',
            name='project_experience',
            field=models.TextField(default='experience', max_length=300),
        ),
    ]
