# Generated by Django 4.0 on 2022-01-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_project_people_project_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name_TS', models.CharField(max_length=120)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='resource_TS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.techsupport'),
        ),
    ]
