# Generated by Django 4.0 on 2022-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_techsupport_project_resource_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='People Owner'),
        ),
    ]
